# Generated by Django 3.0.6 on 2020-05-30 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_assets_name', models.CharField(max_length=255, unique=True, verbose_name='厂商名称')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='增加日期')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('scan_time', models.DateTimeField(auto_now_add=True, verbose_name='上次扫描日期')),
            ],
            options={
                'verbose_name': '厂商名称表',
                'verbose_name_plural': '厂商名称表',
                'ordering': ['-m_time'],
            },
        ),
        migrations.CreateModel(
            name='SRC_platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_platform_name', models.CharField(max_length=254, unique=True, verbose_name='SRC平台名称')),
                ('src_platform_url', models.URLField(unique=True, verbose_name='SRC平台链接')),
                ('src_platform_avatar', models.ImageField(blank=True, default='', upload_to='', verbose_name='SRC平台logo')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='增加日期')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': 'SRC资产平台表',
                'verbose_name_plural': 'SRC资产平台表',
                'ordering': ['-m_time'],
            },
        ),
        migrations.CreateModel(
            name='Target_domain_assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_domain_assets_domain', models.URLField(unique=True, verbose_name='域名')),
                ('target_domain_assets_ip', models.GenericIPAddressField(verbose_name='IP')),
                ('target_domain_assets_localtion', models.CharField(default='', max_length=254, verbose_name='归属地')),
                ('target_domain_assets_port', models.CharField(max_length=32, verbose_name='端口')),
                ('target_domain_assets_service', models.CharField(default='', max_length=256, verbose_name='服务')),
                ('target_domain_assets_title', models.CharField(default='', max_length=500, verbose_name='标题')),
                ('target_domain_assets_middleware', models.CharField(default='', max_length=500, verbose_name='中间件')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='增加日期')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('company_assets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Company_assets', verbose_name='与对应的厂商对应')),
            ],
            options={
                'verbose_name': '主域名资产详细表',
                'verbose_name_plural': '主资产详细表',
                'ordering': ['-m_time'],
            },
        ),
        migrations.CreateModel(
            name='Target_sudomain_assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_subdomain_assets_subdomain', models.URLField(unique=True, verbose_name='子域名')),
                ('target_subdomain_assets_ip', models.GenericIPAddressField(verbose_name='IP')),
                ('target_subdomain_assets_localtion', models.CharField(default='', max_length=254, verbose_name='归属地')),
                ('target_subdomain_assets_port', models.CharField(max_length=32, verbose_name='端口')),
                ('target_subdomain_assets_service', models.CharField(default='', max_length=256, verbose_name='服务')),
                ('target_subdomain_assets_title', models.CharField(default='', max_length=500, verbose_name='标题')),
                ('target_subdomain_assets_middleware', models.CharField(default='', max_length=500, verbose_name='中间件')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='增加日期')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('target_domain_assets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Target_domain_assets', verbose_name='与对应的厂商主域名对应')),
            ],
            options={
                'verbose_name': '子域名资产详细表',
                'verbose_name_plural': '子资产详细表',
                'ordering': ['-m_time'],
            },
        ),
        migrations.CreateModel(
            name='Target_ip_assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_ip_assets_ip', models.GenericIPAddressField(verbose_name='IP')),
                ('target_domain_assets_port', models.CharField(max_length=32, verbose_name='端口')),
                ('target_domain_assets_service', models.CharField(default='', max_length=256, verbose_name='服务')),
                ('target_domain_assets_title', models.CharField(default='', max_length=500, verbose_name='标题')),
                ('target_domain_assets_middleware', models.CharField(default='', max_length=500, verbose_name='中间件')),
                ('target_ip_assets_localtion', models.CharField(default='', max_length=254, verbose_name='归属地')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='增加日期')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('company_assets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Company_assets', verbose_name='与对应的厂商对应')),
            ],
            options={
                'verbose_name': 'IP资产详细表',
                'verbose_name_plural': 'IP资产详细表',
                'ordering': ['-m_time'],
            },
        ),
        migrations.AddField(
            model_name='company_assets',
            name='sec_platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.SRC_platform', verbose_name='与SRC平台连结'),
        ),
        migrations.CreateModel(
            name='Bug_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_info_url', models.CharField(max_length=500, verbose_name='漏洞URL')),
                ('bug_info_type', models.CharField(max_length=255, verbose_name='漏洞类型')),
                ('bug_info_text', models.TextField(default='', max_length=65535, verbose_name='漏洞详细')),
                ('bug_info_submit', models.CharField(choices=[('0', '未提交'), ('1', '已提交')], default='0', max_length=32, verbose_name='漏洞是否提交')),
                ('bug_info_money', models.FloatField(default=0, max_length=32, verbose_name='漏洞奖金')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='增加日期')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('target_domain_assets', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Target_domain_assets', verbose_name='与对应的主域名连结')),
                ('target_ip_assets', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Target_ip_assets', verbose_name='与对应的IP链接')),
                ('target_subdomain_assets', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Target_sudomain_assets', verbose_name='与对应的子域名连结')),
            ],
            options={
                'verbose_name': '漏洞详细表',
                'verbose_name_plural': '漏洞详细表',
                'ordering': ['-m_time'],
            },
        ),
    ]
