# Generated by Django 3.0.6 on 2020-05-30 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_assets',
            old_name='sec_platform',
            new_name='src_platform',
        ),
    ]
