# Generated by Django 3.0.6 on 2020-05-30 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20200530_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='src_platform',
            options={'ordering': ['-m_time'], 'verbose_name': 'SRC平台表', 'verbose_name_plural': 'SRC平台表'},
        ),
        migrations.AlterModelOptions(
            name='target_domain_assets',
            options={'ordering': ['-m_time'], 'verbose_name': '主域名资产详细表', 'verbose_name_plural': '主域名资产详细表'},
        ),
        migrations.AlterModelOptions(
            name='target_ip_assets',
            options={'ordering': ['-m_time'], 'verbose_name': 'IP资产表', 'verbose_name_plural': 'IP资产表'},
        ),
        migrations.AlterModelOptions(
            name='target_sudomain_assets',
            options={'ordering': ['-m_time'], 'verbose_name': '子域名资产详细表', 'verbose_name_plural': '子域名资产详细表'},
        ),
    ]
