# Generated by Django 3.0.6 on 2020-05-31 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20200531_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_ips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_ips_ips', models.CharField(max_length=254, verbose_name='厂商的IP资产')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='增加日期')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Company', verbose_name='与厂商对应')),
            ],
            options={
                'verbose_name': '厂商IP资产',
                'verbose_name_plural': '厂商IP资产',
                'ordering': ['-m_time'],
            },
        ),
        migrations.CreateModel(
            name='Company_domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_domain_domains', models.CharField(max_length=254, verbose_name='厂商的域名资产')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='增加日期')),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Company', verbose_name='与厂商对应')),
            ],
            options={
                'verbose_name': '厂商域名资产',
                'verbose_name_plural': '厂商域名资产',
                'ordering': ['-m_time'],
            },
        ),
        migrations.AlterField(
            model_name='target_ip',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Company_ips', verbose_name='与对应的厂商IP资产对应'),
        ),
        migrations.AlterField(
            model_name='target_sudomain',
            name='target_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Company_domain', verbose_name='与对应的厂商主域名对应'),
        ),
        migrations.DeleteModel(
            name='Target_domain',
        ),
    ]
