# Generated by Django 3.0.6 on 2020-05-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20200531_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug_info',
            name='bug_info_money',
            field=models.FloatField(blank=True, default=0, max_length=32, verbose_name='漏洞奖金'),
        ),
        migrations.AlterField(
            model_name='bug_info',
            name='bug_info_text',
            field=models.TextField(blank=True, default='', max_length=65535, verbose_name='漏洞详细'),
        ),
        migrations.AlterField(
            model_name='target_ip',
            name='target_ip_middleware',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='中间件'),
        ),
        migrations.AlterField(
            model_name='target_ip',
            name='target_ip_service',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='服务'),
        ),
        migrations.AlterField(
            model_name='target_ip',
            name='target_ip_title',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='target_sudomain',
            name='target_subdomain_middleware',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='中间件'),
        ),
        migrations.AlterField(
            model_name='target_sudomain',
            name='target_subdomain_service',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='服务'),
        ),
        migrations.AlterField(
            model_name='target_sudomain',
            name='target_subdomain_statuscode',
            field=models.IntegerField(blank=True, default=200, verbose_name='状态码'),
        ),
        migrations.AlterField(
            model_name='target_sudomain',
            name='target_subdomain_title',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='标题'),
        ),
    ]
